# Fine-Tuning Your Model

In [4]:
# Importing pandas
import pandas as pd

# Importing the course datasets 
diabetes = pd.read_csv('datasets/diabetes_clean.csv')
music = pd.read_csv('datasets/music_clean.csv')
advertising = pd.read_csv('datasets/advertising_and_sales_clean.csv')
telecom = pd.read_csv("datasets/telecom_churn_clean.csv")

## Confusion matrix in scikit-learn

In [ ]:
from sklearn.metrics import confusion_matrix
knn = KNeighborsClassifier(n_neighbors=7)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                   random_state=42)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

## Assessing a diabetes prediction classifier

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

# Veri kümesini oku
diabetes = pd.read_csv('datasets/diabetes_clean.csv')

# 'Outcome' sütununun varlığını kontrol et
if 'Outcome' in diabetes.columns:
    # Bağımsız değişkenleri (X) ve bağımlı değişkeni (y) ayır
    X = diabetes.drop('Outcome', axis=1)
    y = diabetes['Outcome']

    # Veri kümesini eğitim ve test kümelerine ayır
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # KNeighborsClassifier nesnesi oluştur
    knn = KNeighborsClassifier(n_neighbors=6)

    # Modeli eğitim verilerine uydur
    knn.fit(X_train, y_train)

    # Test verilerinin etiketlerini tahmin et: y_pred
    y_pred = knn.predict(X_test)

    # Karmaşıklık matrisini ve sınıflandırma raporunu oluştur
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
else:
    print("Hata: 'Outcome' sütunu veri kümesinde bulunamadı.")


Hata: 'Outcome' sütunu veri kümesinde bulunamadı.


In [ ]:
# Import confusion matrix
from sklearn.metrics import confusion_matrix, classification_report

knn = KNeighborsClassifier(n_neighbors=6)

# Fit the model to the training data
knn.fit(X_train, y_train)

# Predict the labels of the test data: y_pred
y_pred = knn.predict(X_test)

# Generate the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
<script.py> output:
    [[116  35]
     [ 46  34]]
                  precision    recall  f1-score   support
    
               0       0.72      0.77      0.74       151
               1       0.49      0.42      0.46        80
    
        accuracy                           0.65       231
       macro avg       0.60      0.60      0.60       231
    weighted avg       0.64      0.65      0.64       231

## Logistik regression in scikit-learn

In [18]:
import pandas as pd
telecom_churn_clean = pd.read_csv('datasets/telecom_churn_clean.csv')
telecom_churn_clean

Unnamed: 0  account_length  ...  customer_service_calls  churn
0              0             128  ...                       1      0
1              1             107  ...                       1      0
2              2             137  ...                       0      0
3              3              84  ...                       2      0
4              4              75  ...                       3      0
...          ...             ...  ...                     ...    ...
3328        3328             192  ...                       2      0
3329        3329              68  ...                       3      0
3330        3330              28  ...                       2      0
3331        3331             184  ...                       2      0
3332        3332              74  ...                       0      0

[3333 rows x 20 columns]

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,
                                                   random_state=42)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

## Predicting probabilities 

In [ ]:
y_pred_probs = logreg.predict_proba(X_test)[:, 1]
print(y_probs[0])

NameError: name 'X_test' is not defined

In [ ]:
[0.8961376]

## Plotting the ROC Curve

In [ ]:
from sklearn.metrics import roc_curve
fpr, tpr, thresholds = roc_curve(y_test, y_pred_probs)
plt.plot([0, 1], [0, 1], 'k--')
plt.plot(fpr, tpr)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Logistic Regression ROC Curve')
plt.show()

![resim_2023-04-14_132134747](resim_2023-04-14_132134747.png)


## ROC AUC

![resim_2023-04-14_132357807](resim_2023-04-14_132357807.png)


## ROC AUC in scikit-learn

In [ ]:
from sklearn.metrics import 
roc_auc_scoreprint(roc_auc_score(y_test, y_pred_probs))
0.6700964152663693

In [24]:
import pandas as pd
diabetes_df = pd.read_csv('datasets/diabetes_clean.csv')
diabetes_df

pregnancies  glucose  diastolic  triceps  ...   bmi    dpf  age  diabetes
0              6      148         72       35  ...  33.6  0.627   50         1
1              1       85         66       29  ...  26.6  0.351   31         0
2              8      183         64        0  ...  23.3  0.672   32         1
3              1       89         66       23  ...  28.1  0.167   21         0
4              0      137         40       35  ...  43.1  2.288   33         1
..           ...      ...        ...      ...  ...   ...    ...  ...       ...
763           10      101         76       48  ...  32.9  0.171   63         0
764            2      122         70       27  ...  36.8  0.340   27         0
765            5      121         72       23  ...  26.2  0.245   30         0
766            1      126         60        0  ...  30.1  0.349   47         1
767            1       93         70       31  ...  30.4  0.315   23         0

[768 rows x 9 columns]

## Building a logistic regression model

In [ ]:
# Import LogisticRegression
from sklearn.linear_model import LogisticRegression

# Instantiate the model
logreg = LogisticRegression()

# Fit the model
logreg.fit(X_train, y_train)

# Predict probabilities
y_pred_probs = logreg.predict_proba(X_test)[:, 1]

print(y_pred_probs[:10])

<script.py> output:
    [0.26551031 0.18336542 0.12119596 0.15613565 0.49611285 0.44582236
     0.01359235 0.61646125 0.55640546 0.7931187 ]

## The ROC curve
Now we have built a logistic regression model for predicting diabetes status, we can plot the ROC curve to visualize how the true positive rate and false positive rate vary as the decision threshold changes.

In [ ]:
# Import roc_curve
from sklearn.metrics import roc_curve

# Generate ROC curve values: fpr, tpr, thresholds
fpr, tpr, thresholds = roc_curve(y_test, y_pred_probs)

plt.plot([0, 1], [0, 1], 'k--')

# Plot tpr against fpr
plt.plot(fpr, tpr)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve for Diabetes Prediction')
plt.show()

![resim_2023-04-14_132933515](resim_2023-04-14_132933515.png)


## ROC AUC

In [ ]:
# Import roc_auc_score
from sklearn.metrics import roc_auc_score

# Calculate roc_auc_score
print(roc_auc_score(y_test, y_pred_probs))

# Calculate the confusion matrix
print(confusion_matrix(y_test, y_pred))

# Calculate the classification report
print(classification_report(y_test, y_pred))

In [ ]:
0.7300496688741722
[[124  27]
 [ 42  38]]
              precision    recall  f1-score   support

           0       0.75      0.82      0.78       151
           1       0.58      0.47      0.52        80

    accuracy                           0.70       231
   macro avg       0.67      0.65      0.65       231
weighted avg       0.69      0.70      0.69       231

In [ ]:
<script.py> output:
    0.8002483443708608
    [[121  30]
     [ 30  50]]
                  precision    recall  f1-score   support
    
               0       0.80      0.80      0.80       151
               1       0.62      0.62      0.62        80
    
        accuracy                           0.74       231
       macro avg       0.71      0.71      0.71       231
    weighted avg       0.74      0.74      0.74       231

## Hyperparameter tuning
### GridSearchCV in scikit-learn

In [ ]:
from sklearn.model_selection import GridSearchCV
kf = KFold(n_splits=5, shuffle=True, random_state=42)
param_grid = {"alpha": np.arange(0.0001, 1, 10),
              "solver": ["sag", "lsqr"]}
ridge = Ridge()
ridge_cv = GridSearchCV(ridge, param_grid, cv=kf)
ridge_cv.fit(X_train, y_train)
print(ridge_cv.best_params_, ridge_cv.best_score_)

{'alpha': 0.0001, 'solver': 'sag'}
0.7529912278705785

## RandomizedSearchCV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
kf = KFold(n_splits=5, shuffle=True, random_state=42)
param_grid = {'alpha': np.arange(0.0001, 1, 10),
              "solver": ['sag', 'lsqr']}
ridge = Ridge()
ridge_cv = RandomizedSearchCV(ridge, param_grid, cv=kf, n_iter=2)
ridge_cv.fit(X_train, y_train)
print(ridge_cv.best_params_, ridge_cv.best_score_)

{'solver': 'sag', 'alpha': 0.0001}
0.7529912278705785

## Evaulating on the test set

In [ ]:
test_score = ridge_cv.score(X_test, y_test)
print(test_score)

0.7564731534089224

## Hyperparameter tuning with GridSearchCV

In [ ]:
# Import GridSearchCV
from sklearn.model_selection import GridSearchCV

# Set up the parameter grid
param_grid = {"alpha": np.linspace(0.00001, 1, 20)}

# Instantiate lasso_cv
lasso_cv = GridSearchCV(lasso, param_grid, cv=kf)

# Fit to the training data
lasso_cv.fit(X_train, y_train)
print("Tuned lasso paramaters: {}".format(lasso_cv.best_params_))
print("Tuned lasso score: {}".format(lasso_cv.best_score_))

In [ ]:
<script.py> output:
    Tuned lasso paramaters: {'alpha': 1e-05}
    Tuned lasso score: 0.33078807238121977

## Hyperparameter tuning with RandomizedSearchCV

In [ ]:
# Create the parameter space
params = {"penalty": ["l1", "l2"],
         "tol": np.linspace(0.0001, 1.0, 50),
         "C": np.linspace(0.1, 1.0, 50),
         "class_weight": ["balanced", {0:0.8, 1:0.2}]}

# Instantiate the RandomizedSearchCV object
logreg_cv = RandomizedSearchCV(logreg, params, cv=kf)

# Fit the data to the model
logreg_cv.fit(X_train, y_train)

# Print the tuned parameters and score
print("Tuned Logistic Regression Parameters: {}".format(logreg_cv.best_params_))
print("Tuned Logistic Regression Best Accuracy Score: {}".format(logreg_cv.best_score_))

In [ ]:
<script.py> output:
    Tuned Logistic Regression Parameters: {'tol': 0.14294285714285712, 'penalty': 'l2', 'class_weight': 'balanced', 'C': 0.6326530612244898}
    Tuned Logistic Regression Best Accuracy Score: 0.7460082633613221